### ISSUE TITLE
Problem with notebook 7

### ISSUE THREAD

**Issue by prtome** [m-rossi/jupyter-docx-bundler#101]
I just installed the latest versions of of notebook (7.06), nbconvert (7.11) and cox-bundler (0.4.0)

If I run on the command line 
python3 -m jupyter nbconvert --execute --to=docx  2023.ipynb --output 2023.docx

I get te following error:
 `
[NbConvertApp] WARNING | Config option `template_path` not recognized by `DocxExporter`.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/jupyter_core/application.py", line 280, in launch_instance
    super().launch_instance(argv=argv, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/traitlets/config/application.py", line 1053, in launch_instance
    app.start()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbconvert/nbconvertapp.py", line 412, in start
    self.convert_notebooks()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbconvert/nbconvertapp.py", line 579, in convert_notebooks
    self.exporter = cls(config=self.config)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbconvert/exporters/exporter.py", line 123, in __init__
    self._init_preprocessors()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbconvert/exporters/exporter.py", line 293, in _init_preprocessors
    self.register_preprocessor(preprocessor, enabled=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbconvert/exporters/exporter.py", line 253, in register_preprocessor
    preprocessor_cls = import_item(preprocessor)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/traitlets/utils/importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'jupyter_contrib_nbextensions'
`

If I install jupyter_contrib_nbextensions I get instead:

`
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/jupyter-nbconvert", line 5, in <module>
    from nbconvert.nbconvertapp import main
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbconvert/nbconvertapp.py", line 187, in <module>
    class NbConvertApp(JupyterApp):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbconvert/nbconvertapp.py", line 246, in NbConvertApp
    Options include {get_export_names()}.
                     ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbconvert/exporters/base.py", line 151, in get_export_names
    e = get_exporter(exporter_name)(config=config)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbconvert/exporters/base.py", line 110, in get_exporter
    exporter = items[0].load()
               ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/jupyter_contrib_nbextensions/__init__.py", line 5, in <module>
    import jupyter_nbextensions_configurator
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/jupyter_nbextensions_configurator/__init__.py", line 18, in <module>
    from notebook.base.handlers import APIHandler, IPythonHandler
ModuleNotFoundError: No module named 'notebook.base'
`

Which versions of notebook, nbconvert and docx-bundler should I use ? I don't see any issues about this, can you tell me what is wrong with my installation ? it used to work perfectly with notebook 6

Thanks

**Comment by m-rossi** [comment]
Although I do not think it is relevant for your error report, could you please add your pandoc version? `pandoc --version`

**Comment by m-rossi** [comment]
I am sorry I have not catched this issue beforehand. My GitHub actions were disabled somehow. I am running the testsuite now to see if it can find your issue.

**Comment by prtome** [comment]
hello,
here is the version of pandoc: 2.17.1.1

thanks

**Comment by m-rossi** [comment]
Hey @prtome I am sorry, I am unable to reproduce your error with my Python installation. I am guessing the error is related to another (maybe outdated?) package. Please provide either `conda list` or `pip list`.

**Comment by prtome** [comment]
Here is my list
Package                           Version
--------------------------------- ------------
anyio                             4.0.0
appnope                           0.1.3
argon2-cffi                       23.1.0
argon2-cffi-bindings              21.2.0
arrow                             1.3.0
asttokens                         2.4.1
async-lru                         2.0.4
attrs                             23.1.0
Babel                             2.13.1
backcall                          0.2.0
beautifulsoup4                    4.12.2
bleach                            6.1.0
certifi                           2023.11.17
cffi                              1.16.0
charset-normalizer                3.3.2
colorlover                        0.3.0
comm                              0.2.0
contourpy                         1.2.0
cufflinks                         0.17.3
cycler                            0.12.1
debugpy                           1.8.0
decorator                         5.1.1
defusedxml                        0.7.1
docutils                          0.20.1
entrypoints                       0.4
executing                         2.0.1
fastjsonschema                    2.19.0
fonttools                         4.44.3
fqdn                              1.5.1
idna                              3.4
import-ipynb                      0.1.4
ipykernel                         6.26.0
ipython                           8.17.2
ipython-genutils                  0.2.0
ipywidgets                        8.1.1
isoduration                       20.11.0
jedi                              0.19.1
Jinja2                            3.1.2
joblib                            1.3.2
json5                             0.9.14
jsonpointer                       2.4
jsonschema                        4.20.0
jsonschema-specifications         2023.11.1
jupyter_client                    7.4.9
jupyter-contrib-core              0.4.2
jupyter-contrib-nbextensions      0.7.0
jupyter_core                      5.5.0
jupyter-docx-bundler              0.4.0
jupyter-events                    0.9.0
jupyter-highlight-selected-word   0.2.0
jupyter-lsp                       2.2.0
jupyter-nbextensions-configurator 0.6.3
jupyter_server                    2.10.1
jupyter_server_terminals          0.4.4
jupyterlab                        4.0.9
jupyterlab-pygments               0.2.2
jupyterlab_server                 2.25.2
jupyterlab-widgets                3.0.9
kiwisolver                        1.4.5
lxml                              4.9.3
MarkupSafe                        2.1.3
matplotlib                        3.8.2
matplotlib-inline                 0.1.6
mistune                           3.0.2
nbclassic                         1.0.0
nbclient                          0.9.0
nbconvert                         7.11.0
nbformat                          5.9.2
nest-asyncio                      1.5.8
notebook                          7.0.6
notebook_shim                     0.2.3
numpy                             1.26.2
overrides                         7.4.0
packaging                         23.2
pandas                            2.1.3
pandoc                            2.3
pandocfilters                     1.5.0
parso                             0.8.3
pexpect                           4.8.0
pickleshare                       0.7.5
Pillow                            10.1.0
pip                               23.3.1
platformdirs                      4.0.0
plotly                            5.18.0
plumbum                           1.8.2
ply                               3.11
prometheus-client                 0.18.0
prompt-toolkit                    3.0.41
psutil                            5.9.6
ptyprocess                        0.7.0
pure-eval                         0.2.2
pycparser                         2.21
pygame                            2.5.2
Pygments                          2.17.1
pypandoc                          1.12
pyparsing                         3.1.1
python-dateutil                   2.8.2
python-json-logger                2.0.7
pytz                              2023.3.post1
PyYAML                            6.0.1
pyzmq                             24.0.1
referencing                       0.31.0
requests                          2.31.0
rfc3339-validator                 0.1.4
rfc3986-validator                 0.1.1
rpds-py                           0.13.0
scikit-learn                      1.3.2
scipy                             1.11.4
seaborn                           0.13.0
Send2Trash                        1.8.2
setuptools                        68.2.2
six                               1.16.0
sniffio                           1.3.0
soupsieve                         2.5
stack-data                        0.6.3
statistics                        1.0.3.5
tabulate                          0.9.0
tenacity                          8.2.3
terminado                         0.18.0
testpath                          0.6.0
threadpoolctl                     3.2.0
tinycss2                          1.2.1
tornado                           6.3.3
traitlets                         5.13.0
types-python-dateutil             2.8.19.14
tzdata                            2023.3
uri-template                      1.3.0
urllib3                           2.1.0
wcwidth                           0.2.10
webcolors                         1.13
webencodings                      0.5.1
websocket-client                  1.6.4
widgetsnbextension                4.0.9

**Comment by prtome** [comment]
I have run other tests and found this  strange behaviour.

1 - I start jupyterlab, and export from the File menu: no problem

2 - I ran this command from the command line: problem
 python3 -m jupyter nbconvert --execute --to=docx A.ipynb --output A_Atest.docx

I have no idea what is in my environment that causes the problem, or what is called differently between these 2 actions. 

I am happy that at least one of these works, but would be nice to find why.
Thans for your help and this tool

**Comment by m-rossi** [comment]
Just did some experiments with various package downgrades, so the package versions match your versions, no luck.

Two other ideas: 
1. I noticed one thing, you have a lot more jupyter-stuff installed (right is my machine):
  ![](https://github.com/m-rossi/jupyter-docx-bundler/assets/4509134/281a13a6-746b-436c-a44a-cdaed726ae6f)
  Does this result in your experiments with `jupyter_contrib_nbextensions`?
2. Anything special in your jupyter configuration file? May there is some now outdated setting?

**Comment by prtome** [comment]
Thanks - I deleted all the jupyter modules (contrib etc) you don't have and now it works.  and it works.
I put back the "highlight selected word" and it works also so that is no the culprit and that is the only one I use

Thans for your help - now it works so no contrib extensions does the trick

**Comment by m-rossi** [comment]
I am relieved that we were able to solve the problem. It turns out once again that this Jupyter Notebook 7 / JupyterLab 4 update was quite _big_.
