### ISSUE TITLE
Feature request: Parameter to add global cell tags

### ISSUE THREAD

**Issue by fccoelho** [m-rossi/jupyter-docx-bundler#30]
On some conversions it is interesting to hide all input cells. For the Latex converter there is support to templates, which provide an easy way to remove input cells or change the output in other ways. Since you have already defined specific cell tags to remove entire cells or just cell inputs, all that is missing is a way to define this tag only once for all cells.

I have long notebooks which I export to Latex/PDF without cell inputs, I want to export them to docx using this extension but without having to manually annotate every cell.

**Comment by m-rossi** [comment]
You got a point there. Thanks for the recommendation! When I create a long document it also felt stupid to me with the current way. Especially the docx-export in most cases does not need code cells.

Do you have a specific example for a template which has such kind of global tag?

**Comment by m-rossi** [comment]
@fccoelho I have just released [version 0.3.0](https://github.com/m-rossi/jupyter-docx-bundler/releases/tag/0.3.0) which brings some support for your requested feature. This will be extended in future releases.
