### ISSUE TITLE
dead kernel after installation with conda

### ISSUE THREAD

**Issue by JohannaZ** [m-rossi/jupyter-docx-bundler#31]
Hi, 
I just installed the docs-bundler on a py 2.7 environment, now the Kernel dies immediately when I open a jupyter notebook with the py27 kernel. Same notebooks are running if I change the kernel.
Since people are already using it, is this an issue with python 2.7?

**Comment by m-rossi** [comment]
The package requires Python >= 3.6, sorry. Python 2 will reach end of life on January 1, 2020: https://pythonclock.org/

But maybe there are two workarounds for you:
1. Prepare the notebook in the Python 2 Kernel, then switch to the working Python 3 kernel for exporting.
2. Call `jupyter nbconvert --to=docx <source notebook>.ipynb --output <target document>.docx` from a working Python 3 environment.

**Comment by JohannaZ** [comment]
Ah okay, good to now, then I´ll just use one of my Python 3.6 environments. Thanks for the fast reply!
