### ISSUE TITLE
WARNING | Config option `template_path` not recognized by `DocxExporter`

### ISSUE THREAD

**Issue by shinokada** [m-rossi/jupyter-docx-bundler#38]
When I run, I get the following warning.

```
WARNING | Config option `template_path` not recognized by `DocxExporter`
```

What is the best way to remove this warning?

<img width="1437" alt="Screen Shot 2020-04-22 at 10 01 56" src="https://user-images.githubusercontent.com/147320/79929313-58e05a80-8480-11ea-9f4e-18f1e6393d59.png">

**Comment by m-rossi** [comment]
Am I right that you configured the setting `c.DocxExporter.template_path = ['path/to/template']` in your `jupyter_nbconvert_config.py`?

In case you want edit the layout of the exported document:
This exporter/bundler relies on [nbconvert](https://nbconvert.readthedocs.io/en/latest/) and [pandoc](https://www.pandoc.org) which both can use templates. However the main layout is based on the pandoc-template. How to modify this template is described [here](https://github.com/m-rossi/jupyter-docx-bundler/wiki/Custom-export-template).

**Comment by shinokada** [comment]
Thanks.

1. I have  ~/.jupyter/jupyter_nbconvert_config.json, but not ~/.jupyter/jupyter_nbconvert_config.py.
2. My ~/.jupyter/jupyter_nbconvert_config.json is the following. If I need to add `c.DocxExporter.template_path =/Users/shinokada/.pandoc/reference.docx`, where should I place it? Should it be under template_path?


```
{
  "version": 1,
  "Exporter": {
    "template_path": [
      ".",
      "/usr/local/lib/python3.7/site-packages/jupyter_contrib_nbextensions/templates",
      "/Users/shinokada/virtualenvs/jupyter/lib/python3.7/site-packages/jupyter_contrib_nbextensions/templates",
      "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_contrib_nbextensions/templates",
      "/Users/shinokada/.pyenv/versions/3.8.2/envs/py382/lib/python3.8/site-packages/jupyter_contrib_nbextensions/templates"
    ],
    "preprocessors": [
      "jupyter_contrib_nbextensions.nbconvert_support.CodeFoldingPreprocessor",
      "jupyter_contrib_nbextensions.nbconvert_support.PyMarkdownPreprocessor"
    ]
  }
}
```

**Comment by m-rossi** [comment]
Ok, right now it‘s not clear to me why the warning is shown to you, because you have not defined `c.DocxExporter.template_path` anywhere. I have to try a few things tomorrow.

The template in `/Users/shinokada/.pandoc/reference.docx` is used automatically by pandoc during export.

**Comment by m-rossi** [comment]
It seems like your configuration in `~/.jupyter/jupyter_nbconvert_config.json` applies to all nbconvert converters, so also for `jupyter-docx-bundler`.

If you are using templates for other export formats I would recommend to ignore the warning. As I mentioned above the template in `/Users/shinokada/.pandoc/reference.docx` is used automatically.

**Comment by shinokada** [comment]
Thanks for your reply.

For the record, this is my  ~/.jupyter/jupyter_nbconvert_config.json.

```
$ cat ~/.jupyter/jupyter_nbconvert_config.json
{
  "version": 1,
  "Exporter": {
    "template_path": [
      ".",
      "/usr/local/lib/python3.7/site-packages/jupyter_contrib_nbextensions/templates",
      "/Users/shinokada/virtualenvs/jupyter/lib/python3.7/site-packages/jupyter_contrib_nbextensions/templates",
      "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_contrib_nbextensions/templates",
      "/Users/shinokada/.pyenv/versions/3.8.2/envs/py382/lib/python3.8/site-packages/jupyter_contrib_nbextensions/templates"
    ],
    "preprocessors": [
      "jupyter_contrib_nbextensions.nbconvert_support.CodeFoldingPreprocessor",
      "jupyter_contrib_nbextensions.nbconvert_support.PyMarkdownPreprocessor"
    ]
  }
}
```

Is the `template_path` making the warning or `preprocessor`?

**Comment by m-rossi** [comment]
It is `template_path`.
