### ISSUE TITLE
No export for multiple (matplotlib)-images in output cell 

### ISSUE THREAD

**Issue by m-rossi** [m-rossi/jupyter-docx-bundler#39]
The following code creates 5 images in cell, however only the first one gets exported.
```python
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

for ii in np.arange(5):
    plt.figure()
    plt.plot(np.arange(100)**2)
    plt.show()
```

**Comment by kirschma** [comment]
Hi Marco,
I had the same problem exporting with pandas versions higher than 2.6. Up to 2.6 the export works fine. Just give this a try. Maybe this helps you to find the reason.
The cause for not exporting all images lies somewhere in pandas. Even tried to convert a document directly using pandas without any other tool showed this behaviour.
Best regards Martin

**Comment by m-rossi** [comment]
I don't think it has to do with the pandas version. Could you explain which specific version you mean? They had version numbers to 0.25 and then switched to 1.0. Currently we have 1.0.5.

However this package basically does a conversion to `*.html` and then to `*.docx`. You can try it with
```sh
jupyter-nbconvert notebook.ipynb --to html
pandoc notebook.html --to docx -o notebook.docx
```
The `*.html` has all the images, however the `*.docx` not. The issue seems to be in the conversion process of pandoc.

**Comment by m-rossi** [comment]
Just after submitting my comment, I understood: you meant pandoc :-)

**Comment by m-rossi** [comment]
May its time to remove that `*.html`-intermediate conversion because pandoc supports direct `*.ipynb`-conversion since [version 2.6](https://github.com/jgm/pandoc/releases/tag/2.6)
