### ISSUE TITLE
Development environment

### ISSUE THREAD

**Issue by obearn** [m-rossi/jupyter-docx-bundler#49]
I can't setup development environment, pandoc requirements cannot be satisfied :
```shell
ERROR: Could not find a version that satisfies the requirement pandoc>=2.7 (from -r requirements.txt (line 3)) (from versions: 1.0.0a0, 1.0.0a3, 1.0.0a6, 1.0.0a7, 1.0.0a8, 1.0.0a12, 1.0.0a13, 1.0.0a14, 1.0.0a16, 1.0.0a17, 1.0.0a18, 1.0.0a19, 1.0.0b1, 1.0.0b2, 1.0.0b3, 1.0.0, 1.0.1, 1.0.2, 2.0a1, 2.0a2, 2.0a3, 2.0a4)
ERROR: No matching distribution found for pandoc>=2.7 (from -r requirements.txt (line 3))
```

**Comment by obearn** [comment]
I was trying to install with pip, and figured out that some requirements are conda-forge requirements. Just modified requirements files to allow pip installation. Tests are ok. Separating conda and python dependencies could be interesting if not installed with conda.

**Comment by m-rossi** [comment]
That's right the `README` does not contain the steps to setup a development environment, just for testing it in a conda-installation, thanks for that hint! The requirement are internally used just for the GitHub-CI.

I will try to edit the `README` with the necessary steps later today, I just quickly tested a pip only development install, please follow these steps:
1. Make sure you have [Pandoc](https://pandoc.org) installed, see [installing-pandoc](https://github.com/bebraw/pypandoc#installing-pandoc) for instructions.
2. Execute `pip install -e .` This command should install all necessary requirements using pip and install `jupyter-docx-bundler` in _editable_-mode
3. Execute `jupyter bundlerextension enable --py jupyter_docx_bundler --sys-prefix`
