### ISSUE TITLE
Sympy equations ?

### ISSUE THREAD

**Issue by Mike-HubGit** [m-rossi/jupyter-docx-bundler#73]
**Describe the bug**
LaTeX equations display well in Mardown mode (for example $a^3=5$ in a markdown section is well exported to Word) Whereas sympy results are not. Is this a bug or there is a specific way to render equations for docx-bundler ?

**To reproduce**
What works : in a Markdown cell :  $a^3=5$
What does not work : in a python cell :
import sympy as sp
sp.var("a b c")
from IPython.display import display
display((a/b)**3)

**Expected behavior**
What would be beautiful would be to export this to word too !

**Screenshots**
in Jupyter :
![Capture d’écran 2021-05-03 à 23 03 04](https://user-images.githubusercontent.com/65092924/116933407-cf06c800-ac63-11eb-910b-eaf62c47081f.png)
in LibreOffice :
![Capture d’écran 2021-05-03 à 23 04 09](https://user-images.githubusercontent.com/65092924/116933472-e0e86b00-ac63-11eb-98e1-475c18160c23.png)

**Desktop (please complete the following information):**
- OS: Linux Mint XFCE 20
- Browser Chrome and Firefox
- Versions of Python packages, find out with `pip list````

pip list
Package                            Version
---------------------------------- -------------------
actionlib                          1.13.2
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 2.0.1
anaconda-project                   0.9.1
angles                             1.9.13
anyio                              2.2.0
appdirs                            1.4.4
argh                               0.26.2
argon2-cffi                        20.1.0
asn1crypto                         1.4.0
astroid                            2.5
astropy                            4.0.2
async-generator                    1.10
atomicwrites                       1.4.0
attrs                              20.3.0
autopep8                           1.5.6
Babel                              2.9.0
backcall                           0.2.0
backports.functools-lru-cache      1.6.4
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
beautifulsoup4                     4.9.3
bitarray                           1.9.2
bkcharts                           0.2
bleach                             3.3.0
bokeh                              2.3.1
bondpy                             1.8.6
boto                               2.49.0
Bottleneck                         1.3.2
brotlipy                           0.7.0
camera-calibration                 1.15.3
camera-calibration-parsers         1.12.0
catkin                             0.8.9
certifi                            2020.12.5
cffi                               1.14.5
chardet                            4.0.0
click                              7.1.2
cloudpickle                        1.6.0
clyent                             1.2.2
colorama                           0.4.4
conda                              4.10.1
conda-build                        3.21.4
conda-package-handling             1.7.3
conda-repo-cli                     1.0.3
conda-token                        0.2.0
conda-verify                       3.4.2
contextlib2                        0.6.0.post1
control                            0.9.0
controller-manager                 0.19.4
controller-manager-msgs            0.19.4
cryptography                       3.4.7
cv-bridge                          1.15.0
cycler                             0.10.0
Cython                             0.29.23
cytoolz                            0.11.0
dask                               2021.4.0
decorator                          4.4.2
defusedxml                         0.7.1
diagnostic-analysis                1.10.3
diagnostic-common-diagnostics      1.10.3
diagnostic-updater                 1.10.3
diff-match-patch                   20200713
distributed                        2021.4.0
docutils                           0.16
dynamic-reconfigure                1.7.1
entrypoints                        0.3
et-xmlfile                         1.0.1
fastcache                          1.1.0
filelock                           3.0.12
flake8                             3.9.0
Flask                              1.1.2
fsspec                             0.9.0
future                             0.18.2
gazebo-plugins                     2.9.1
gazebo-ros                         2.9.1
gencpp                             0.6.5
geneus                             3.0.0
genlisp                            0.4.18
genmsg                             0.5.16
gennodejs                          2.0.2
genpy                              0.6.14
gevent                             21.1.2
glob2                              0.7
gmpy2                              2.0.8
greenlet                           1.0.0
h5py                               2.10.0
HeapDict                           1.0.1
html5lib                           1.1
idna                               2.10
image-geometry                     1.15.0
imageio                            2.9.0
imagesize                          1.2.0
importlib-metadata                 3.10.0
iniconfig                          1.1.1
interactive-markers                1.12.0
intervaltree                       3.1.0
ipykernel                          5.3.4
ipython                            7.22.0
ipython-genutils                   0.2.0
ipywidgets                         7.6.3
isort                              5.8.0
itsdangerous                       1.1.0
jdcal                              1.4.1
jedi                               0.17.1
jeepney                            0.6.0
Jinja2                             2.11.3
joblib                             1.0.1
joint-state-publisher              1.15.0
joint-state-publisher-gui          1.15.0
json5                              0.9.5
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     6.1.12
jupyter-console                    6.4.0
jupyter-core                       4.7.1
jupyter-docx-bundler               0.3.2
jupyter-packaging                  0.7.12
jupyter-server                     1.4.1
jupyterlab                         3.0.14
jupyterlab-pygments                0.1.2
jupyterlab-server                  2.4.0
jupyterlab-widgets                 1.0.0
keyring                            22.3.0
kiwisolver                         1.3.1
laser-geometry                     1.6.7
lazy-object-proxy                  1.6.0
libarchive-c                       2.9
llvmlite                           0.36.0
locket                             0.2.1
lxml                               4.6.3
MarkupSafe                         1.1.1
matplotlib                         3.3.4
mccabe                             0.6.1
message-filters                    1.15.9
mistune                            0.8.4
mkl-fft                            1.3.0
mkl-random                         1.1.1
mkl-service                        2.3.0
mock                               4.0.3
more-itertools                     8.7.0
mpmath                             1.2.1
msgpack                            1.0.2
multipledispatch                   0.6.0
navigator-updater                  0.2.1
nbclassic                          0.2.6
nbclient                           0.5.1
nbconvert                          6.0.7
nbformat                           5.1.3
nest-asyncio                       1.4.2
networkx                           2.5.1
nltk                               3.6.1
nose                               1.3.7
notebook                           6.3.0
numba                              0.53.1
numexpr                            2.7.3
numpy                              1.19.2
numpydoc                           1.1.0
olefile                            0.46
openpyxl                           3.0.7
packaging                          20.9
pandas                             1.2.4
pandocfilters                      1.4.3
parso                              0.7.0
partd                              1.2.0
path                               15.1.2
pathlib2                           2.3.5
pathtools                          0.1.2
patsy                              0.5.1
pep8                               1.7.1
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             8.2.0
pip                                21.0.1
pkginfo                            1.7.0
pluggy                             0.13.1
ply                                3.11
prometheus-client                  0.10.1
prompt-toolkit                     3.0.17
psutil                             5.8.0
ptyprocess                         0.7.0
py                                 1.10.0
pycodestyle                        2.6.0
pycosat                            0.6.3
pycparser                          2.20
pycurl                             7.43.0.6
pydocstyle                         6.0.0
pyee                               7.0.4
pyflakes                           2.2.0
Pygments                           2.8.1
pylint                             2.7.4
PyMeasure                          0.9.0
pyodbc                             4.0.0-unsupported
pyOpenSSL                          20.0.1
pypandoc                           1.5
pyparsing                          2.4.7
pyppeteer                          0.2.2
pyqtgraph                          0.11.0
pyrsistent                         0.17.3
pyserial                           3.5
PySocks                            1.7.1
pytest                             6.2.3
python-dateutil                    2.8.1
python-jsonrpc-server              0.4.0
python-language-server             0.35.1
python-qt-binding                  0.4.3
pytz                               2021.1
pyusb                              1.1.1
PyVISA                             1.11.3
PyVISA-py                          0.5.2
PyWavelets                         1.1.1
pyxdg                              0.27
PyYAML                             5.4.1
pyzmq                              20.0.0
QDarkStyle                         3.0.2
qt-dotgraph                        0.4.2
qt-gui                             0.4.2
qt-gui-cpp                         0.4.2
qt-gui-py-common                   0.4.2
QtAwesome                          1.0.2
qtconsole                          5.0.3
QtPy                               1.9.0
regex                              2021.4.4
requests                           2.25.1
resource-retriever                 1.12.6
rope                               0.18.0
rosbag                             1.15.9
rosboost-cfg                       1.15.7
rosclean                           1.15.7
roscreate                          1.15.7
rosgraph                           1.15.9
roslaunch                          1.15.9
roslib                             1.15.7
roslint                            0.12.0
roslz4                             1.15.9
rosmake                            1.15.7
rosmaster                          1.15.9
rosmsg                             1.15.9
rosnode                            1.15.9
rosparam                           1.15.9
rospy                              1.15.9
rosservice                         1.15.9
rostest                            1.15.9
rostopic                           1.15.9
rosunit                            1.15.7
roswtf                             1.15.9
rqt-action                         0.4.9
rqt-bag                            0.5.1
rqt-bag-plugins                    0.5.1
rqt-console                        0.4.11
rqt-dep                            0.4.10
rqt-graph                          0.4.14
rqt-gui                            0.5.2
rqt-gui-py                         0.5.2
rqt-image-view                     0.4.16
rqt-launch                         0.4.9
rqt-logger-level                   0.4.11
rqt-moveit                         0.5.9
rqt-msg                            0.4.9
rqt-nav-view                       0.5.7
rqt-plot                           0.4.13
rqt-pose-view                      0.5.10
rqt-publisher                      0.4.9
rqt-py-common                      0.5.2
rqt-py-console                     0.4.9
rqt-reconfigure                    0.5.3
rqt-robot-dashboard                0.5.8
rqt-robot-monitor                  0.5.13
rqt-robot-steering                 0.5.12
rqt-runtime-monitor                0.5.8
rqt-rviz                           0.6.1
rqt-service-caller                 0.4.9
rqt-shell                          0.4.10
rqt-srv                            0.4.8
rqt-tf-tree                        0.6.2
rqt-top                            0.4.9
rqt-topic                          0.4.12
rqt-web                            0.4.9
Rtree                              0.9.7
ruamel-yaml-conda                  0.15.100
rviz                               1.14.5
scikit-image                       0.18.1
scikit-learn                       0.24.1
scipy                              1.6.2
seaborn                            0.11.1
SecretStorage                      3.3.1
Send2Trash                         1.5.0
sensor-msgs                        1.13.1
setuptools                         52.0.0.post20210125
simplegeneric                      0.8.1
singledispatch                     0.0.0
sip                                4.19.13
six                                1.15.0
slycot                             0.4.0.0
smach                              2.5.0
smach-ros                          2.5.0
smclib                             1.8.6
sniffio                            1.2.0
snowballstemmer                    2.1.0
sortedcollections                  2.1.0
sortedcontainers                   2.3.0
soupsieve                          2.2.1
Sphinx                             3.5.4
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             1.0.3
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.4
sphinxcontrib-websupport           1.2.4
spyder                             4.1.5
spyder-kernels                     1.9.4
SQLAlchemy                         1.4.7
statsmodels                        0.12.2
sympy                              1.8
tables                             3.6.1
tabulate                           0.8.9
tblib                              1.7.0
terminado                          0.9.4
testpath                           0.4.4
tf                                 1.13.2
tf-conversions                     1.13.2
tf2-geometry-msgs                  0.7.5
tf2-kdl                            0.7.5
tf2-py                             0.7.5
tf2-ros                            0.7.5
threadpoolctl                      2.1.0
tifffile                           2020.10.1
toml                               0.10.2
toolz                              0.11.1
topic-tools                        1.15.9
tornado                            6.1
tqdm                               4.59.0
traitlets                          5.0.5
typing-extensions                  3.7.4.3
ujson                              4.0.2
unicodecsv                         0.14.1
urllib3                            1.26.4
watchdog                           1.0.2
wcwidth                            0.2.5
webencodings                       0.5.1
websockets                         8.1
Werkzeug                           1.0.1
wheel                              0.36.2
widgetsnbextension                 3.5.1
wrapt                              1.12.1
wurlitzer                          2.1.0
xacro                              1.14.6
xlrd                               2.0.1
XlsxWriter                         1.3.8
xlwt                               1.3.0
xmltodict                          0.12.0
yapf                               0.31.0
zict                               2.0.0
zipp                               3.4.1
zope.event                         4.5.0
zope.interface                     5.3.0
```
- Pandoc version `pandoc --version`
```
 pandoc --version
pandoc 2.12
Compiled with pandoc-types 1.22, texmath 0.12.1.1, skylighting 0.10.4,
citeproc 0.3.0.8, ipynb 0.1.0.1
User data directory: /home/eea/.local/share/pandoc
Copyright (C) 2006-2021 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```
**Additional context**

**Comment by m-rossi** [comment]
@Mike-HubGit thanks for the report.

> Is this a bug or there is a specific way to render equations for docx-bundler ?

Looks like equations in output of cells are treated differently than in markdown cells. I had something similiar with tables. I will look into that issue later today and report back.

**Comment by m-rossi** [comment]
As expected, the cell contains two outputs:
```python
{'text/plain': 'a/b**3', 'text/latex': '$\\displaystyle \\frac{a}{b^{3}}$'}
```
Pandoc choses `'text/plain'` as it seems it cannot convert the latex formula. I will try to find a workaround for this.

**Comment by Mike-HubGit** [comment]
Very nice ! thanks a lot !

**Comment by m-rossi** [comment]
@Mike-HubGit I think I solved the issue and will release a new version over the weekend.

**Comment by Mike-HubGit** [comment]
Yeah so nice !! Will allow to make easy reports that include symbolic computation, that's juste wonderful !
Thanks a lot !
